# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: express lambda CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test And Style Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run lint:fix
      
  deploy:
    name: Force Deploy
    runs-on: ubuntu-latest
    needs: test


    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Remove duplicates
        run: npm dedupe

      - name: Remove unused dependencies
        run: npm prune
      
      - name: Zip current folder
        run: |
          zip -r send-express.zip .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
          --function-name express \
          --zip-file fileb://send-express.zip